export const config: any = {
 
    'HOST': 'http://admin.pleinairapp.com:3014/',
    'HOST_URL' : "http://admin.pleinairapp.com/pleineir/#/",
    
    'API_URL': 'https://join.pleinairapp.com/api/',
    'ADMIN_PHOTO_ENDPOINT': 'https://join.pleinairapp.com/uploads/',
    'USER_PHOTO' : 'http://admin.pleinairapp.com/pleineir/server/',
    'PHOTO_ENDPOINT' : 'https://join.pleinairapp.com/uploads/',
    'AUTH_URL': 'auth/local',
    'QUERY': 'query/',
    'QUERYEXE': 'query/execute/conditions/',
    'BULK': 'bulk/insert/',
    'SOFT': 'soft/',
    'USERS': 'users/',
    'LOGIN': 'login',
    'RESETPWD': 'forgetPassword',
    'COMMON' : 'commons/',
    'ABOUT' : 'aboutUs',
    'CONTACT' : 'contactUs',
    'SESSION' : 'Session/',
    'POP' : 'POP/',
    'POPS' : 'pops/',
    'USER' : 'User/',
    'FIND_SESSION' : 'sessions/find',
    'UPLOADS' : 'view/head/server/public/uploads',
    'UPDATE' : 'updateInfo',
    'CHANGE_PWD' :'changepassword',
    'PUBLIC' : '/public',
    'GET_BY_ID' : 'adminById',
    'PRIVATE' : '/private',
    'ADD_ABOUT' :'add/aboutus',
    'ADD_PRIVACY' :'add/privacypolicy',
    'ADD_TERMS' :'add/termsandcondition',
    'DELETEFAQ' : 'soft/FAQ/',
    'FAQ' : 'FAQ/',
    'US' : 'User/',
    'ANNOUNCE':'Announcement/',
    'SESSIONS':'sessions/',
    'DELETE':'delete/',
    'UPDATES' : 'update/',
    'CURRENCY' :'Currency/',
    'IMAGE':'image/',
   'FAV_POP' :'favoritePop',
   'FAV_SESSION' : 'favoriteSession',
   'BOOK' :'bookingSession',
   'USER_FAV_SESSION' : 'usersOfFavSession',
   'USER_FAV_POP' : 'usersOfFavPop',
   'USER_BOOK' : 'usersOfbookedSession',
   'GET_PIE_CHART' : 'getPieChart',
    'PAYMENT' : 'paymentinfo',
    
};
